# Generated by Django 2.1.1 on 2018-10-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20181017_1030'),
        ('profiles', '0003_auto_20181017_0816'),
    ]

    operations = [
    ]
