# Generated by Django 2.1.1 on 2018-10-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_merge_20181017_1533'),
        ('profiles', '0004_merge_20181017_1224'),
    ]

    operations = [
    ]
