# Generated by Django 2.1.1 on 2018-10-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181016_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
