# Generated by Django 2.1.1 on 2018-10-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181016_1206'),
        ('articles', '0004_article_image'),
    ]

    operations = [
    ]
