# Generated by Django 2.1.1 on 2018-10-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_reported_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reported',
            options={'ordering': ['-created_at']},
        ),
    ]
