# Generated by Django 2.1.1 on 2018-10-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20181018_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='reported',
            name='times_reported',
            field=models.IntegerField(default=0),
        ),
    ]
