# Generated by Django 2.1.1 on 2018-10-19 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_merge_20181019_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='published_on',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
