# Generated by Django 2.1.1 on 2018-10-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecomment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
