# Generated by Django 2.1.1 on 2018-10-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20181017_1143'),
        ('comments', '0002_commenthistory'),
    ]

    operations = [
    ]
