# Generated by Django 2.1.1 on 2018-10-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20181017_1136'),
        ('comments', '0002_commenthistory'),
    ]

    operations = [
    ]
