# Generated by Django 2.1.1 on 2018-10-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_merge_20181017_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
